In [ ]:
import numpy as np

In [ ]:
a = np.array([6, 7, 8])

In [ ]:
print(type(a)) 

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(3,)


In [ ]:
print(a[0], a[1], a[2])

6 7 8


In [ ]:
a[0] = 9

In [ ]:
print(a)

[9 7 8]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(b.shape) 

(2, 3)


In [ ]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [ ]:
a = np.zeros([2,2])
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones([2,4])
print(b) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
c = np.full([2,2], 8)
print(c) 

[[8 8]
 [8 8]]


In [ ]:
d = np.eye(5)
print(d) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
e = np.random.random([3,4])
print(e) 

[[0.10062928 0.39052689 0.44996661 0.02899217]
 [0.13294036 0.31393413 0.67437128 0.54807077]
 [0.44677686 0.35343079 0.66313578 0.82744244]]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
r1 = a[1, :]
r2 = a[1:2, :] 

In [ ]:
print(r1,r1.shape)
print(r2,r2.shape) #i didnt got this sir

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b = np.array([0, 2, 0, 1])
print(b)

[0 2 0 1]


In [ ]:
print(a[np.arange(4), b])

[ 1  6  7 11]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y=x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
np.sin(b)

array([[-0.07991469, -0.13481033,  0.88419972],
       [ 0.87079385,  0.27329299,  0.41976402]])

In [ ]:
np.tan(b)

array([ 0.        , -2.18503986,  0.        ,  1.55740772])

In [ ]:
np.arctan(b)

array([0.        , 1.10714872, 0.        , 0.78539816])

In [ ]:
np.around(np.arctan(b))

array([0., 1., 0., 1.])

In [ ]:
np.fix(np.tan(b))

array([ 0., -2.,  0.,  1.])

In [ ]:
np.ceil(np.tan(b))

array([ 0., -2.,  0.,  2.])

In [ ]:
np.floor(np.tan(b))

array([ 0., -3.,  0.,  1.])

In [ ]:
np.log(y)

array([[0.69314718, 0.69314718, 1.38629436],
       [1.60943791, 1.60943791, 1.94591015],
       [2.07944154, 2.07944154, 2.30258509],
       [2.39789527, 2.39789527, 2.56494936]])

In [ ]:
np.exp(y)

array([[1.43703950e-01, 1.24285967e+01, 3.08766427e+01],
       [5.51468706e+01, 1.55089132e+02, 1.18264716e-03]])

In [ ]:
a = np.array([[1.94,-2.52,3.43],[-4.01,5.044,6.74]])
b = np.array([[-0.08,9.56,8.34],[7.34,6.56,-5.85]])

In [ ]:
y=np.copysign(a,b)

In [ ]:
print(y)

[[-1.94   2.52   3.43 ]
 [ 4.01   5.044 -6.74 ]]


In [ ]:
y=np.nextafter(b,a)
print(y)

[[-0.08  9.56  8.34]
 [ 7.34  6.56 -5.85]]


In [ ]:
y=np.spacing(b,a)
print(y)

[[-1.38777878e-17  1.77635684e-15  1.77635684e-15]
 [ 8.88178420e-16  8.88178420e-16 -8.88178420e-16]]


In [ ]:
y=np.frexp(b,a)
print(y)

(array([[-0.64   ,  0.5975 ,  0.52125],
       [ 0.9175 ,  0.82   , -0.73125]]), array([[-3,  4,  4],
       [ 3,  3,  3]], dtype=int32))


In [ ]:
a=np.array([2,3,4])
b=np.array([6,4,3])

In [ ]:
y=np.lcm(b,a)
print(y)

[ 6 12 12]


In [ ]:
y=np.gcd(b,a)
print(y)

[2 1 1]


In [ ]:
y=np.add(b,a)
print(y)

[8 7 7]


In [ ]:
y=np.reciprocal(b,a)
print(y)

[0 0 0]


In [ ]:
y=np.positive(b,a)
print(y)

[6 4 3]


In [ ]:
y=np.negative(b,a)
print(y)

[-6 -4 -3]


In [ ]:
y=np.multiply(b,a)
print(y)

[12 12 12]


In [ ]:
y=np.divide(b,a)
print(y)

[3.         1.33333333 0.75      ]


In [ ]:
y=np.power(b,a)
print(y)

[36 64 81]


In [ ]:
y=np.subtract(b,a)
print(y)

[ 4  1 -1]


In [ ]:
y=np.true_divide(b,a)
print(y)

[-1. -1. -1.]


In [ ]:
y=np.floor_divide(b,a)
print(y)

[-1 -1 -1]


In [ ]:
y=np.float_power(b,a)
print(y)

[2.14334705e-05 3.90625000e-03 3.70370370e-02]


In [ ]:
y=np.fmod(b,a)
print(y)

[0 0 0]


In [ ]:
y=np.remainder(b,a)
print(y)

[0 0 0]
